services:
  - type: web
    name: bio-link-protector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        sync: false
      - key: DATABASE_NAME
        value: bio_link_protector
      - key: DEFAULT_DELETE_SECONDS
        value: "0"
      - key: MAX_DELETE_SECONDS
        value: "86400"
      - key: MT_API_ID
        sync: false
      - key: MT_API_HASH
        sync: false
      - key: MT_SESSION
        sync: false
